name: Branch Cleanup

on:
    schedule:
        - cron: "0 0 * * *"  # It will trigger every hour 

jobs:
    cleanup:
        runs-on: ubuntu-latest
        steps:
        # Checkout the repository code
        - name: Checkout code
          uses: actions/checkout@v2

        # Remove unused Branches
        - name: Clean up unused Branches
          run: |
            git fetch --prune
            git branch --merged master | grep -v "master" | xargs -n 1 git branch -d             
