name: Resource Optimization Workflow

on: 
    push:

jobs:
    build-and-test:
        strategy:
            fail-fast: true 
            matrix: 
                os: [ubuntu-latest, macos-latest]
                python-version: [3.8, 3.9, 3.10.1]
            # max-parallel: 2
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout Code 
              uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip 
                pip install -r requirements.txt
            - name: Run tests 
              run: python -m pytest

    deploy:
        needs: build-and-test
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to production
              run: |
                # Run deployment script here
                echo "Deployment successfull"

